### PR TITLE
fix:Handle gRPC messages larger than max size

### LINKED ISSUE #370: grpc: received message larger than max
I got this error when I run a tests. I guess the target HTTP server response a big body.

This is API that I call `/server.Runner/RunTestCase`

image
image

## How to reproduce it
You can setup an easy HTTP server to response a big body.

## Background tech
You need to know the basic knowledge of `gRPC`. See also the following answer:

* https://stackoverflow.com/questions/55362342/grpc-received-message-larger-than-max-8653851-vs-4194304

### PR DESCRIPTION
**Pull request by acceleratorssr**
**What type of PR is this?**
[backend][bug][good first issue]
Functional improvements

**What this PR does / why we need it**:
fix: grpc: received message larger than max

grpc now checks in advance for messages exceeding the default maximum receive limit of 4MB and returns a friendly error message indicating that the HTTP response content is too long.

After running the make test, there were no errors or failures reported in the end

**Which issue(s) this PR fixes**:

Fixes #370

### CODE REVIEW

File: pkg/runner/http.go [hunk 1]
```diff
@@ -47,6 +47,8 @@ type ReportResult struct {
 	LastErrorMessage string
 }
 
+const DefaultMaxRecvMsgSize = 4194304
```
Comment (LinuxSuRen) [inline pkg/runner/http.go:50]: How do you get this value? Is there any document about it? You can put that link here.

Or, if it is possible to get this value from `gRPC` library.

File: pkg/runner/http.go [hunk 2]
```diff
@@ -258,6 +260,11 @@ func (r *simpleTestCaseRunner) GetSuggestedAPIs(suite *testing.TestSuite, api st
 
 func (r *simpleTestCaseRunner) withResponseRecord(resp *http.Response) (responseBodyData []byte, err error) {
 	responseBodyData, err = io.ReadAll(resp.Body)
+	if len(responseBodyData) > DefaultMaxRecvMsgSize {
+		err = fmt.Errorf("HTTP response body is too large")
+		return
+	}
+
```
Comment (LinuxSuRen) [inline pkg/runner/http.go:267]: Actually, HTTP response does not have this limit. The `gRPC` do. I prefer to set the limit in the `gRPC` response function. For example:

https://github.com/LinuxSuRen/api-testing/blob/e9974374b116dc0f7de540027410b3f2350bf7a5/pkg/server/remote_server.go#L444

File: pkg/runner/http.go (hunk 1 above)
Comment (LinuxSuRen) [reply pkg/runner/http.go:50]: See also https://github.com/grpc/grpc-go/blob/d32e66ce27447a0a217464a36fdd3935801c0453/rpc_util.go#L351

Comment (acceleratorssr) [reply pkg/runner/http.go]: Thank you for your help. Before submitting my initial PR, I considered retrieving this value from the gRPC library, but I couldn't locate the corresponding setting. It appears that only the maximum message limit for receiving by gRPC clients can be configured. Therefore, I've decided to update the approach: explicitly setting the maximum message limit for receiving upon establishing a gRPC connection (initially set to the default 4MB). Subsequently, I will return this value in the response function of gRPC, allowing for size determination along with the response body.

**Comment by Ink-33** [comment]
In my opinion, we can try to increase the limition of size, and control it in configuration.

File: pkg/runner/http.go (hunk 1 above)
Comment (Ink-33) [reply pkg/runner/http.go]: I found this by searching `4 * 1024 * 1024`, and this two value seems to be unexported.

Comment (LinuxSuRen) [reply pkg/runner/http.go]: It looks like an internal const. We are not able to use it.

**Comment by LinuxSuRen** [comment]
> In my opinion, we can try to increase the limition of size, and control it in configuration.

Agree. We can add a CLI flag to set it. For example: `atest server --grpc-max-recv-msg-size`. And keep the default value of it.

File: pkg/testing/case.go [hunk 3]
```diff
@@ -56,13 +56,14 @@ type Secure struct {
...
-	Request Request  `yaml:"request" json:"request"`
-	Expect  Response `yaml:"expect,omitempty" json:"expect,omitempty"`
+	ID                 string   `yaml:"id,omitempty" json:"id,omitempty"`
+	Name               string   `yaml:"name,omitempty" json:"name,omitempty"`
+	Group              string   `yaml:"group,omitempty" json:"group,omitempty"`
+	Before             *Job     `yaml:"before,omitempty" json:"before,omitempty"`
+	After              *Job     `yaml:"after,omitempty" json:"after,omitempty"`
+	Request            Request  `yaml:"request" json:"request"`
+	Expect             Response `yaml:"expect,omitempty" json:"expect,omitempty"`
+	GrpcMaxRecvMsgSize int      `yaml:"grpc_max_recv_msg_size,omitempty" json:"grpc_max_recv_msg_size,omitempty"`
```
Comment (LinuxSuRen) [inline pkg/testing/case.go:66]: I guess we don't need to add this field here. Because it is never used.

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]

File: pkg/testing/case.go (hunk 3 above)
Comment (acceleratorssr) [reply pkg/testing/case.go:66]: I intend to utilize GrpcMaxRecvMsgSize to determine the size of the command line settings stored in the server type. Then, the testCase can establish a gRPC connection and set the appropriate receive size accordingly. However, I'm uncertain if this approach is overly complex or if there might be any potential issues.

Comment (LinuxSuRen) [reply pkg/testing/case.go:66]: IMO, it might be not safe if allow users to set the limit for each request. For example, A give it a very big value, then send  too many requests. the server might let the server panic.

For now, I believe a global setting is enough.

Comment (acceleratorssr) [reply pkg/testing/case.go:66]: may I understand that setting restrictions on the command line isn't necessary, and can I directly establish a 4MB constant in pkg/server/remote_server.go to check if the response body is too large?

Comment (LinuxSuRen) [reply pkg/testing/case.go:66]: I agree with adding a flag to the CLI to set the limit. I think it's not necessary to add it into `type TestCase struct {`. Others are ok to me.

**Review by LinuxSuRen — APPROVED** [review]
LGTM

**Comment by LinuxSuRen** [comment]
Welcome to be the 19th contributor. Let's build a stronger open-source project.

**Comment by acceleratorssr** [comment]
Thank you, I will keep studying.
